import Link from "next/link";
import { Hero } from "@/components/Hero";
import { getPosts, getProducts } from "@/lib/contentStore";
import { WrenchScrewdriverIcon, ComputerDesktopIcon, CodeBracketIcon, PaintBrushIcon } from "@heroicons/react/24/outline";
export const dynamic = "force-dynamic";
const services=[{icon:WrenchScrewdriverIcon,title:"Computer care",text:"A fresh start for your everyday tech. Reliable repairs, upgrades, and support.",tag:"REPAIR & SUPPORT"},{icon:ComputerDesktopIcon,title:"The right tech",text:"Equipment that works as hard as you do. Find the right tools for your next step.",tag:"IT EQUIPMENT"},{icon:CodeBracketIcon,title:"Web experiences",text:"Your ideas deserve a home online. Thoughtful websites, built around your business.",tag:"DESIGN & DEVELOPMENT"},{icon:PaintBrushIcon,title:"Design that speaks",text:"Stand out and tell your story with memorable logos, posters, and visual identities.",tag:"GRAPHIC DESIGN"}];
export default async function Home(){
 const [products,posts]=await Promise.all([getProducts(),getPosts()]);
 const recent=[...posts].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).slice(0,2);
 return <><Hero/><div className="expertise-strip"><div className="shell"><span>A LITTLE OF WHAT WE DO</span><b>Build better.</b><i>✳</i><b>Think creatively.</b><i>✳</i><b>Learn something new.</b><i>✳</i><b>Go further.</b></div></div>
 <section className="shell section" id="services"><div className="section-heading"><div><div className="eyebrow">01 / WHAT WE DO</div><h2>Good people.<br/>Great digital solutions.</h2></div><p>Practical support. Thoughtful design. Real possibilities.<br/>Everything you need to take your next step, all in one place.</p></div><div className="services-grid">{services.map((s,i)=><a href={i===1?"/product":"#contact"} className="service-card" key={s.title}><div className="service-top"><s.icon/><span>0{i+1}</span></div><span className="card-eyebrow">{s.tag}</span><h3>{s.title}</h3><p>{s.text}</p><span className="card-arrow" aria-hidden="true">↗</span></a>)}</div></section>
 <section className="about-section" id="about"><div className="shell about-grid"><div className="about-symbol" aria-hidden="true">✳<span>LOCAL ROOTS. DIGITAL REACH.</span></div><div><div className="eyebrow">MORE THAN TECHNOLOGY</div><h2>A digital future.<br/>For all of us.</h2><p>We’re Shan Cyber. We help young people and businesses turn curiosity into capability, with practical digital skills, creative services, and technology that makes everyday life better.</p><a className="text-link" href="https://www.youtube.com/@kltechtips163" target="_blank" rel="noopener noreferrer">Get to know our community <span>↗</span></a></div></div></section>
 <section className="shell section"><div className="section-heading"><div><div className="eyebrow">02 / MADE FOR YOU</div><h2>Small tools. Big possibilities.</h2></div><Link className="text-link" href="/product">Explore all products <span>↗</span></Link></div><div className="product-grid">{products.slice(0,3).map((p,i)=><a className="product-card" key={p.id} href={p.link} target="_blank" rel="noopener noreferrer"><div className={`product-art product-art-${i}`} aria-hidden="true">{i===0?<><span className="game-team">←</span><span className="game-rope"/><span className="game-team">→</span><small>PLAY. LEARN. TOGETHER.</small></>:i===1?<div className="keyboard"><b>Make every keystroke count.</b><div>{"QWERTYUIOP".split("").map(k=><span key={k}>{k}</span>)}</div><div>{"ASDFGHJKL".split("").map(k=><span key={k}>{k}</span>)}</div><div>{"ZXCVBNM".split("").map(k=><span key={k}>{k}</span>)}</div></div>:<div className="excel-art">X <span>Learn by doing.<br/><small>Build your spreadsheet skills.</small></span></div>}</div><div className="product-info"><span className="card-eyebrow">DIGITAL TOOLS</span><h3>{p.title} <span>↗</span></h3><p>{p.description}</p></div></a>)}</div></section>
 <section className="shell section journal-section"><div className="section-heading"><div><div className="eyebrow">03 / KEEP YOUR CURIOSITY</div><h2>A little knowledge goes a long way.</h2></div><Link className="text-link" href="/blog">Visit the journal <span>↗</span></Link></div><div className="journal-grid">{recent.map(p=><Link className="journal-card" key={p.id} href={`/blog/${p.id}`}><div className="journal-visual"><span>THE DIGITAL<br/>WORLD, EXPLAINED.</span><b>↗</b></div><div><span className="card-eyebrow">{p.date} · JOURNAL</span><h3>{p.title}</h3><p>{p.excerpt}</p><span className="text-link">Read the story ↗</span></div></Link>)}</div></section>
 <section className="shell faq-section"><div><div className="eyebrow">A FEW HELPFUL ANSWERS</div><h2>Curious? Start here.</h2></div><div>{[["What can Shan Cyber help me with?","We provide computer repairs, IT equipment, web design and development, and graphic design. We also share practical digital learning resources."],["Where can I start learning?","Explore our digital tools or visit our YouTube channel for practical technology tips and tutorials."],["How do I discuss a project?","Reach out through our Facebook page using the contact link below. Tell us what you have in mind so we can discuss the next steps."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="shell contact-section" id="contact"><div><div className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h2>Have an idea?<br/>Let’s make it happen.</h2></div><div><p>A question, a project, or just a spark of an idea.<br/>We’d love to hear from you.</p><a className="button button-dark" href="https://www.facebook.com/profile.php?id=100091377146699" target="_blank" rel="noopener noreferrer">Let’s start a conversation <span>↗</span></a></div><span className="contact-star" aria-hidden="true">✳</span></section></>;
}
